wekan:
  image: mquandalle/wekan
  restart: always
  links:
    - wekandb
  environment:
    - MONGO_URL=mongodb://wekandb/wekan
    - ROOT_URL=http://mytodo.org
    - MAIL_URL=
    - MAIL_FROM=
  ports:
    - 8081:80

wekandb:
   image: mongo
   restart: always
   volumes:
     - /home/wekan/data:/data/db


